export const interpretationLibrary = [
  {
    id: "relationship-dynamics",
    audience: "relationship",
    categories: ["synastry", "composite", "davison", "marx"],
    sectionId: "dynamic",
    title: "关系动力学",
    body: "关系盘优先看互动节奏、依附方式与长期协作感，先分清吸引、磨合与承诺三条线。",
    tags: ["relationship", "dynamic", "bonding"],
    entryPointKind: "aspect",
  },
  {
    id: "timing-window",
    audience: "timing",
    categories: [
      "transit",
      "progression",
      "composite-progression",
      "davison-progression",
      "marx-progression",
      "tertiary-progression",
      "composite-tertiary-progression",
      "davison-tertiary-progression",
      "marx-tertiary-progression",
    ],
    sectionId: "timing",
    title: "时间窗口",
    body: "推运类图盘先看推进体、触发相位与锚点日期，再判断当前是适合推进、整理还是观察。",
    tags: ["timing", "forecast", "window"],
    entryPointKind: "placement",
  },
  {
    id: "self-structure",
    audience: "self",
    categories: ["natal"],
    sectionId: "self-pattern",
    title: "结构主轴",
    body: "本命盘阅读先抓核心驱动力、情绪归属与现实执行方式，再向关系与事业两条支线展开。",
    tags: ["self", "pattern", "identity"],
    entryPointKind: "placement",
  },
  {
    id: "overlay-reading",
    audience: "timing",
    categories: ["transit", "progression", "solar-arc", "tertiary-progression"],
    sectionId: "timing",
    title: "Overlay 宫位阅读",
    body: "当 overlay 存在时，先把推进体飞入的宫位当成事件落点，再回看原本宫位与宫主星。",
    tags: ["overlay", "houses", "timing"],
    entryPointKind: "overlay",
  },
  {
    id: "relationship-overlay-reading",
    audience: "timing",
    categories: [
      "composite-progression",
      "davison-progression",
      "marx-progression",
      "composite-tertiary-progression",
      "davison-tertiary-progression",
      "marx-tertiary-progression",
    ],
    sectionId: "timing",
    title: "关系推运落点",
    body: "关系推运先看基础关系盘，再看推运盘怎样飞入这段关系的既有结构，避免把短期触发误当成关系本体。",
    tags: ["relationship", "overlay", "timing"],
    entryPointKind: "overlay",
  },
  {
    id: "marx-dual-perspective",
    audience: "relationship",
    categories: ["marx", "marx-progression", "marx-tertiary-progression"],
    sectionId: "dynamic",
    title: "双视角马克思盘",
    body: "马克思盘必须分别看双方视角，先辨认谁在主导长期黏性，再比较两边的情绪推进是否同步。",
    tags: ["marx", "dual-perspective", "long-term"],
    entryPointKind: "group",
  },
  {
    id: "marx-bond-pattern",
    audience: "relationship",
    categories: ["marx"],
    sectionId: "marx-bond",
    title: "长期关系粘性",
    body: "阅读马克思盘时，要先比较双方视角里的安全感来源和长期绑定方式，再判断谁在维持关系温度、谁在承担关系结构。",
    tags: ["marx", "bonding", "long-term", "relationship"],
    entryPointKind: "group",
  },
  {
    id: "composite-progression-pulse",
    audience: "timing",
    categories: ["composite-progression"],
    sectionId: "relationship-timing",
    title: "关系节奏脉冲",
    body: "组合盘次限更适合用来观察关系本体的阶段推进，不要直接替代比较盘或本命盘的个体体验。",
    tags: ["composite-progression", "relationship", "timing", "progression"],
    entryPointKind: "overlay",
  },
];
