export const interpretationLibrary = [
  {
    id: "relationship-dynamics",
    audience: "relationship",
    categories: ["synastry", "composite", "davison", "marx"],
    sectionId: "dynamic",
    title: "关系动力学",
    body: "关系盘优先看互动节奏、依附方式与长期协作感，先分清吸引、磨合与承诺三条线。",
    tags: ["relationship", "dynamic", "bonding"],
    entryPointKind: "aspect",
  },
  {
    id: "timing-window",
    audience: "timing",
    categories: [
      "transit",
      "progression",
      "composite-progression",
      "davison-progression",
      "marx-progression",
      "tertiary-progression",
      "composite-tertiary-progression",
      "davison-tertiary-progression",
      "marx-tertiary-progression",
    ],
    sectionId: "timing",
    title: "时间窗口",
    body: "推运类图盘先看推进体、触发相位与锚点日期，再判断当前是适合推进、整理还是观察。",
    tags: ["timing", "forecast", "window"],
    entryPointKind: "placement",
  },
  {
    id: "self-structure",
    audience: "self",
    categories: ["natal"],
    sectionId: "self-pattern",
    title: "结构主轴",
    body: "本命盘阅读先抓核心驱动力、情绪归属与现实执行方式，再向关系与事业两条支线展开。",
    tags: ["self", "pattern", "identity"],
    entryPointKind: "placement",
  },
  {
    id: "overlay-reading",
    audience: "timing",
    categories: ["transit", "progression", "solar-arc", "tertiary-progression"],
    sectionId: "timing",
    title: "Overlay 宫位阅读",
    body: "当 overlay 存在时，先把推进体飞入的宫位当成事件落点，再回看原本宫位与宫主星。",
    tags: ["overlay", "houses", "timing"],
    entryPointKind: "overlay",
  },
  {
    id: "relationship-overlay-reading",
    audience: "timing",
    categories: [
      "composite-progression",
      "davison-progression",
      "marx-progression",
      "composite-tertiary-progression",
      "davison-tertiary-progression",
      "marx-tertiary-progression",
    ],
    sectionId: "timing",
    title: "关系推运落点",
    body: "关系推运先看基础关系盘，再看推运盘怎样飞入这段关系的既有结构，避免把短期触发误当成关系本体。",
    tags: ["relationship", "overlay", "timing"],
    entryPointKind: "overlay",
  },
  {
    id: "marx-dual-perspective",
    audience: "relationship",
    categories: ["marx", "marx-progression", "marx-tertiary-progression"],
    sectionId: "dynamic",
    title: "双视角马克思盘",
    body: "马克思盘必须分别看双方视角，先辨认谁在主导长期黏性，再比较两边的情绪推进是否同步。",
    tags: ["marx", "dual-perspective", "long-term"],
    entryPointKind: "group",
  },
  {
    id: "marx-bond-pattern",
    audience: "relationship",
    categories: ["marx"],
    sectionId: "marx-bond",
    title: "长期关系粘性",
    body: "阅读马克思盘时，要先比较双方视角里的安全感来源和长期绑定方式，再判断谁在维持关系温度、谁在承担关系结构。",
    tags: ["marx", "bonding", "long-term", "relationship"],
    entryPointKind: "group",
  },
  {
    id: "composite-progression-pulse",
    audience: "timing",
    categories: ["composite-progression"],
    sectionId: "relationship-timing",
    title: "关系节奏脉冲",
    body: "组合盘次限更适合用来观察关系本体的阶段推进，不要直接替代比较盘或本命盘的个体体验。",
    tags: ["composite-progression", "relationship", "timing", "progression"],
    entryPointKind: "overlay",
  },
  {
    id: "synastry-bridge-pattern",
    audience: "relationship",
    categories: ["synastry"],
    sectionId: "synastry-bridge",
    title: "比较盘触发点",
    body: "比较盘要先辨认谁更容易触发吸引、谁更容易触发防御，再判断双方互动是互补还是拉扯。",
    tags: ["synastry", "relationship", "contact"],
    entryPointKind: "group",
  },
  {
    id: "composite-core-pattern",
    audience: "relationship",
    categories: ["composite"],
    sectionId: "composite-core",
    title: "关系本体结构",
    body: "组合盘更像关系本体本身，适合先看共同需求与共同目标，再分辨这段关系怎样形成自己的重心。",
    tags: ["composite", "relationship", "core"],
    entryPointKind: "group",
  },
  {
    id: "davison-reality-pattern",
    audience: "relationship",
    categories: ["davison"],
    sectionId: "davison-reality",
    title: "关系现实容器",
    body: "时空中点盘更适合观察关系落到现实之后的节奏、容器与现实协作方式，不必直接代替双方个人体验。",
    tags: ["davison", "relationship", "reality"],
    entryPointKind: "group",
  },
  {
    id: "davison-progression-pulse",
    audience: "timing",
    categories: ["davison-progression"],
    sectionId: "davison-progression-timing",
    title: "时空中点推运节奏",
    body: "时空中点盘次限更适合观察关系在现实层面的阶段转向，先看推进体落点，再判断现实节奏是否要调整。",
    tags: ["davison-progression", "relationship", "timing", "progression"],
    entryPointKind: "overlay",
  },
  {
    id: "marx-progression-pulse",
    audience: "timing",
    categories: ["marx-progression"],
    sectionId: "marx-progression-timing",
    title: "马克思盘推运节奏",
    body: "马克思盘次限要分别比较双方视角的推进体，再判断长期关系里的主动方与回应方有没有同步移动。",
    tags: ["marx-progression", "relationship", "timing", "dual-perspective"],
    entryPointKind: "overlay",
  },
  {
    id: "composite-tertiary-pulse",
    audience: "timing",
    categories: ["composite-tertiary-progression"],
    sectionId: "composite-tertiary-timing",
    title: "组合盘三限脉冲",
    body: "组合盘三限更适合看较短周期里的关系情绪波动，先看推进体飞入位置，再判断阶段性敏感点。",
    tags: ["composite-tertiary-progression", "relationship", "timing", "tertiary"],
    entryPointKind: "overlay",
  },
  {
    id: "davison-tertiary-pulse",
    audience: "timing",
    categories: ["davison-tertiary-progression"],
    sectionId: "davison-tertiary-timing",
    title: "时空中点三限脉冲",
    body: "时空中点盘三限适合观察现实互动节奏的短周期起伏，先辨认触发点，再判断需要协调的现实落点。",
    tags: ["davison-tertiary-progression", "relationship", "timing", "tertiary"],
    entryPointKind: "overlay",
  },
  {
    id: "marx-tertiary-pulse",
    audience: "timing",
    categories: ["marx-tertiary-progression"],
    sectionId: "marx-tertiary-timing",
    title: "马克思盘三限脉冲",
    body: "马克思盘三限要同时比较双方视角的短周期情绪推进，再看谁更快进入变化、谁更慢跟上关系节奏。",
    tags: ["marx-tertiary-progression", "relationship", "timing", "dual-perspective", "tertiary"],
    entryPointKind: "overlay",
  },
];
